apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: mongo-service # używana przez flaska a nie mongo. musi się zgadzać z nazwą serwisu mongo, dzięki temu flask wie gdzie ma się podłączyć