apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: bW9uZ3VzZXI= # base64 encoded value of "mongouser"
  mongo-password: bW9uZ3Bhc3N3b3Jk # base64 encoded value of "mongopassword"