apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-public
spec:
  ingressClassName: nginx
  rules:
  - host: app.local
    http:
      paths:
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 8080